[build]
  publish = "packages/.vitepress/dist"
  command = "npm run build && npm run docs:build"

[[redirects]]
  from = "/v4.1.1/*"
  to = "https://6028131f303ad00007a6228b--vueuse.netlify.app/:slug"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
  NODE_VERSION = "14"
