name: Unit Test

on:
  push:
    branches:
      - main
      - dev
      - next

  pull_request:
    branches:
      - main
      - dev
      - next

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i -g pnpm @antfu/ni
    - run: nci
    - name: Lint
      run: nr lint
    - name: Test Vue 3
      run: nr test:3
    - name: Test Vue 2
      run: nr test:2
