name: Unit Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Test for Vue 2.x
      run: |
        npm run switch 2
        npm test
    # - name: Test for Vue 3.x
    #   run: |
    #     npm run switch 3
    #     npm test
    - name: Build for Vue 2.x
      run: npm run build 2
    - name: Build for Vue 3.x
      run: npm run build 3
